### ISSUE TITLE
data 

### ISSUE THREAD

**Issue by Lj4040** [StuartMesham/gector_experiment_public#1]
After dividing the lang-8 data set, I found that the number of training sets of lang-8 error data is not consistent with the number of correct training sets, but the number of validation sets is the same. However, when I run the file utils/preprocess_data.py later, the number of inconsistent, how do you solve the problem? I really need your help. Thank you for your work

**Comment by StuartMesham** [comment]
Hi @Lj4040, I'm not able to reproduce the issue. See [this notebook](https://colab.research.google.com/drive/1zFOjkOX7bqhQlS4h2MdeH0qjxFSPqnfm). For both the `train` and `dev` sets of lang-8, the number of uncorrected examples matches the number of corrected examples (see the output of the `wc -l` commands in the last two cells of the notebook).

Let me know if this helps.

**Comment by Lj4040** [comment]
@StuartMesham Sincerely thank you for your answer, resolved
