### ISSUE TITLE
transformers version

### ISSUE THREAD

**Issue by Lj4040** [StuartMesham/gector_experiment_public#2]
What is the version of your transformers? I use the windows platform, so I don't know the version of your transformers。Thank you for your answer。

**Comment by Lj4040** [comment]
Could you please share your trained model? If it is convenient for you, thank you for your answer

**Comment by Lj4040** [comment]
As I was not clear about the version of transformers, I selected transformers version 4.21.1 in the requirement-inference.txt file, but there seemed to be some problems when I ran run_gector.py
![Snipaste_2023-03-06_11-45-01](https://user-images.githubusercontent.com/117823125/223101427-7a95d0e6-cb6a-4009-bef4-ea68fb8d256f.png)
However, I found that there was only datasets library in requirement, but no dataset, and I installed the version 2.3.2 you gave
I really need your reply. Thank you

**Comment by StuartMesham** [comment]
Hi Lj4040, the code doesn't use a "dataset" library. It only uses the "datasets" library.

[This Colab notebook](https://colab.research.google.com/drive/1kXJZkkqxWf8LQCAAEQGSJ0j5IQSttM2V) shows an example of downloading a trained model and running inference.
